const EN = {
    car: "Car",
    home: "Home",
    life: "Life",
    pets: "Pets",
    compareQuotesMain: "Compare quotes and get the best",
    getQuotes: "Get Quotes",
    beenHereBefore: "Been here before?",
    getYourQuotesBack: "Get your quotes back",
    phoneNumber: "Phone number",
    zipCode: "Enter Zip Code",
    titleCustomizedFree: "Get free, customized quotes in under 3 minutes",
    compareQuotes: "Compare customized quotes",
    compareQuotesDesc: "We'll offer precise, real-time quotes after you answer a few questions.",
    onePlaceDiscounts: "One place for all discounts",
    onePlaceDiscountsDesc:
        "Get all of the discounts you're eligible for in one place. Look around for the best deal in insurance.",
    buyOnline: "Call or buy online",
    buyOnlineDesc:
        "You can buy the policy you want and customize it to your needs right on the website, or arrange a phone call with an agent.",
    limitedOffers: "Limited Offers",
    hearItFromCustomers: "Hear it from our customers",
    seeAllReviews: "See all reviews by our customer",
    whyCompareWith: "Why compare with Policy24?",
    signSavings: "Significant Savings",
    signSavingsDesc:
        "Policy24 users who shop around and compare rates save an average of AED 996 per year on insurance.",
    accessDiscounts: "Access Discounts",
    accessDiscountsDesc: "Take advantage of exclusive pricing and savings opportunities.",
    noHiddenCost: "No hidden costs, ever",
    noHiddenCostDesc: "Everything is as it appears. In one place, you can compare real quotes.",
    getItBy: "Get it by phone or online",
    getItByDesc: "We give you the freedom to choose how and when you get insurance.",
    compareWithTopRated: "Compare quotes from top-rated companies",
    getYourDose: "Get your dose of insurance news, tips, and tricks",
    lookingToSafe: "Looking to save smarter?",
    viewMyQuotes: "View my quotes",
    trustExpertise: "Expertise You Can Trust",
    trustExpertiseDesc:
        "By signing this pledge, you commit to partnering with a company backed by decades of experience, ensuring you receive the most comprehensive and personalized insurance solutions.",
    customerApproach: "Customer-Centric Approach",
    customerApproachDesc:
        "This pledge reinforces our shared promise to prioritize your needs, providing exceptional customer service and tailored plans to safeguard your assets and loved ones.",
    empoweringKnowledge: "Empowering You with Knowledge",
    empoweringKnowledgeDesc:
        "Together, we pledge to build your understanding of insurance, empowering you to make informed decisions that align with your unique financial goals and circumstances.",
    company: "Company",
    legal: "Legal",
    terms: "Term & conditions",
    privacy: "Privacy",
    social: "Social",
    facebook: "Facebook",
    inst: "Instagram",
    whatsapp: "Whatsapp",
    twitter: "Twitter",
    mobile: "800 (Policy24) 72 93 22",
    schedule: "Monday - Sunday: 10:00 AM to 04:00 PM, and 08:00 PM to 02:00 AM",
    credentials:
        "Policy24 FZ LLC is authorized and regulated by the UAE Central Bank. Policy24 FZ LLC is a registered Price Comparison Website (PCW) by the Central Bank with registration number 14. Policy24 FZ LLC© all rights reserved 2023.",
    licence: "Licensed By Central Bank of UAE License Number 14",
    learnMore: "Learn more",
    compareAndSave: "Compare & save",
    newsMockText:
        "This pledge reinforces our shared promise to prioritize your needs, providing exceptional customer service and tailored plans to safeguard your assets and loved ones.",
    newsMockTitle: "Chubb names Benoit Chasseguet Country President for France",
    firstCustomerName: "Yazid Nassif",
    secondCustomerName: "Mustapha Shams",
    thirdCustomerName: "Abal Ibrahim",
    fourthCustomerName: "Qantara Eid",
    customerMockText:
        "I have been using them for a year now. Everything is detailed and well organized and, of course, damn beautiful.",
    letsStartBrand: "Let’s start by picking your brand",
    whatModel: "What is the model of your",
    manufacturerYear: "What is the year of manufacture for your",
    whereRegister: "Where will you register your",
    whatIsValue: "What is the value of your",
    anyInsuranceClaims: "Do you have any previous insurance claims?",
    uaeLicenceLong: "How long do you have license in UAE?",
    fillTheInfo: "Fill the contact information and get your quote now",
    formSubmitted: "Form Submitted Successfully",
    weWillSendOffers: "We Will Send the Best Offers to WhatsApp",
    weSendInsurance: "We Send you Car Insurance Documents",
    thanks: "THANK YOU",
    shippersInTouch:
        "One of our Personal Shoppers is working on your custom quote and will be in touch shortly",
    manuallyEnter: "Manually Enter",
    youAreDone: "You are done with 1 of 3 Steps",
    findBrand: "Find your brand",
    findModel: "Find model",
    findYear: "Find year",
    whereRegisterPH: "Where register",
    insuranceClaims: "Insurance claims",
    uaeLicence: "UAE Licence",
    contactInfo: "Contact info",
    firstName: "First Name",
    lastName: "Last Name",
    emailAddress: "Email address",
    mobileNumber: "Mobile Number",
    dateOfBirth: "Date of birth",
    nationality: "Nationality"
};
export default EN;
